name = "آرمان حسن پور"
# avatar = "images/profile.png" # Avatar image. Default to "images/profile.webp".
bio = "برنامه نویس فول استک"
copyright = "آرمان حسن پور"
rating = "General"
app = "Arsin.ir"

[params]
  #layout = "compact"
  
[social]
  email = "arman.hassanpoor2000@gmail.com"
  github = "arman-hpp"
  twitter = "arman_hasanpour"
  linkedin = "arsin"